package net.faultlinesmp.ships;

import java.util.HashMap;
import java.util.Map;

/**
 * GENERATED by tools/wild_assets.py: don't edit. For each "wild" model part (item model faultline:wild/<part>):
 * {display scale, offset x, y, z}. Java item models are drawn small to fit; an ItemDisplay showing one at scale k
 * needs scale = k * s and translation = Q0 * (k * offset) (offset in the part's own frame: +x front, +z right) so the
 * part's origin sits on the entity at its real size. Bedrock draws the same part full size (an armor stand's helmet).
 */
final class WildParts {
    static final Map<String, double[]> P = new HashMap<>();
    static {
        P.put("lev_head", new double[]{2.45106, -0.10000, 1.77659, -0.00000});
        P.put("lev_body", new double[]{1.25957, -0.00000, 0.75936, -0.00000});
        P.put("lev_tail", new double[]{2.31489, -2.07500, 0.07234, -0.00000});
        P.put("worm_head", new double[]{1.56596, 0.80000, 0.72893, -0.00000});
        P.put("worm_body", new double[]{1.32085, -0.02500, 0.50128, -0.00000});
        P.put("worm_tail", new double[]{1.73617, -1.35000, 1.48425, -0.00000});
        P.put("wyrm_body", new double[]{1.66809, -0.15000, 0.00213, -0.00000});
        P.put("wyrm_neck", new double[]{1.00000, -0.00000, 0.93000, -0.00000});
        P.put("wyrm_head", new double[]{1.73617, 0.45000, 1.68426, -0.00000});
        P.put("wyrm_wing_l", new double[]{2.44085, -1.20000, 3.64128, -3.58500});
        P.put("wyrm_wing_r", new double[]{2.44085, -1.20000, 3.64128, 3.58500});
        P.put("wyrm_tail", new double[]{1.00000, -0.00000, 0.97000, -0.00000});
        P.put("wyrm_tail_tip", new double[]{1.00000, -0.75000, 0.88000, -0.00000});
        P.put("lich", new double[]{1.46383, 0.01000, 1.64575, -0.00000});
        P.put("golem_body", new double[]{1.39574, 0.03000, 2.09362, -0.00000});
        P.put("golem_head", new double[]{1.00000, 0.16500, 1.15000, -0.00000});
        P.put("golem_arm", new double[]{1.31745, 0.06500, -1.77383, 0.01500});
        P.put("golem_leg", new double[]{1.00000, 0.20000, -0.80000, -0.00000});
        P.put("mimic_base", new double[]{1.00000, 0.08500, 1.50000, -0.00000});
        P.put("mimic_lid", new double[]{1.00000, 0.48000, 1.36000, 0.00500});
        P.put("locust", new double[]{1.00000, 0.09000, 1.32000, -0.00000});
        P.put("ghost_captain", new double[]{1.00000, 0.21000, 1.10000, -0.00000});
        P.put("aurora", new double[]{8.17021, -0.00000, 12.25532, -0.00000});
        P.put("black_sun", new double[]{9.53191, -0.00000, 14.29787, -0.00000});
    }

    static double[] of(String part) { return P.getOrDefault(part, new double[]{1, 0, 0, 0}); }
}
