package net.faultlinesmp.items;

import java.util.HashMap;
import java.util.Map;

/**
 * GENERATED by tools/wild_assets.py: don't edit. For each "wild" model part (item model faultline:wild/<part>):
 * {display scale, offset x, y, z}. Java item models are drawn small to fit; an ItemDisplay showing one at scale k
 * needs scale = k * s and translation = Q0 * (k * offset) (offset in the part's own frame: +x front, +z right) so the
 * part's origin sits on the entity at its real size. Bedrock draws the same part full size (an armor stand's helmet).
 */
final class WildParts {
    static final Map<String, double[]> P = new HashMap<>();
    static {
        P.put("lev_head", new double[]{1.90638, -0.10000, 1.90958, -0.00000});
        P.put("lev_body", new double[]{1.08255, -0.00000, 0.54383, -0.00000});
        P.put("lev_tail", new double[]{1.53191, -1.55000, 0.79787, -0.00000});
        P.put("worm_head", new double[]{1.44681, 0.72500, 0.65021, -0.00000});
        P.put("worm_body", new double[]{1.25617, -0.02500, 0.44425, -0.00000});
        P.put("worm_tail", new double[]{1.56596, -1.10000, 1.34894, -0.00000});
        P.put("wyrm_body", new double[]{1.19149, -0.00000, -0.16276, -0.00000});
        P.put("wyrm_head", new double[]{1.20851, 1.77500, 1.13277, -0.00000});
        P.put("wyrm_wing_l", new double[]{1.53191, -1.12500, 2.29787, -2.25000});
        P.put("wyrm_wing_r", new double[]{1.53191, -1.12500, 2.29787, 2.25000});
        P.put("wyrm_tail", new double[]{1.00000, -0.00000, 1.05000, -0.00000});
        P.put("lich", new double[]{1.14723, 0.05000, 1.37085, 0.03000});
        P.put("golem_body", new double[]{1.15745, 0.04000, 1.73617, -0.00000});
        P.put("golem_arm", new double[]{1.15745, -0.00000, -1.56383, -0.00000});
        P.put("golem_leg", new double[]{1.00000, 0.15000, -0.80000, -0.00000});
        P.put("mimic_base", new double[]{1.00000, 0.08500, 1.50000, -0.00000});
        P.put("mimic_lid", new double[]{1.00000, 0.48000, 1.36000, 0.00500});
        P.put("locust", new double[]{1.00000, 0.09000, 1.32000, -0.00000});
        P.put("ghost_captain", new double[]{1.00000, 0.21000, 1.10000, -0.00000});
        P.put("aurora", new double[]{8.17021, -0.00000, 12.25532, -0.00000});
    }

    static double[] of(String part) { return P.getOrDefault(part, new double[]{1, 0, 0, 0}); }
}
